Natalie/fix who is oncall
apiaryio/hubot-pager-me pull request #6
Opened 2020-12-02 12:51 UTC by Mnau-mnau

custom on call

2020-12-03 16:09 UTC, abtris requested changes

2020-12-03 16:09 UTC, abtris commented on src/scripts/pagerduty-custom.coffee
> +    userSupports = json.oncalls.filter((oncall) -> oncall.schedule.id is 'PDHLWLB')
Wasn't this as environment variables (`PDHLWLB`) ?

2020-12-03 16:09 UTC, abtris commented on src/scripts/pagerduty-custom.coffee
> +    "schedule_ids[]": ['PDHLWLB' , 'PGWSC3H', 'PGFERYM'],
The same issue here, we used env variables for this.

2020-12-03 16:09 UTC, abtris commented
@Mnau-mnau I see only issue in hardcoded values with PD ID's

2020-12-03 23:00 UTC, Mnau-mnau commented
I have split the variables, I guess it would have to be defined somewhere where we run Jarvis as well

2020-12-04 10:46 UTC, abtris approved these changes

2020-12-04 10:55 UTC, merged